################################################################################
# Automatically-generated file. Do not edit!
################################################################################

TODISASSEMBLE_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
TODISASSEMBLE_SRCS := 
O_SRCS_QUOTED := 
LD_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
O_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS_QUOTED := 
TOPREPROCESS_SRCS_OS_FORMAT := 
CPP_SRCS := 
O_SRCS := 
C_UPPER_SRCS_OS_FORMAT := 
ELF_SRCS := 
TOPREPROCESS_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
C++_SRCS_QUOTED := 
CXX_SRCS := 
C_SRCS_QUOTED := 
CXX_SRCS_OS_FORMAT := 
S_SRCS_QUOTED := 
ELF_SRCS_QUOTED := 
ELF_SRCS_OS_FORMAT := 
CC_SRCS_OS_FORMAT := 
ASM_SRCS_OS_FORMAT := 
C_UPPER_SRCS_QUOTED := 
C_SRCS_OS_FORMAT := 
ASM_SRCS := 
CC_SRCS_QUOTED := 
S_UPPER_SRCS_OS_FORMAT := 
CXX_SRCS_QUOTED := 
S_UPPER_SRCS := 
CPP_SRCS_QUOTED := 
ASM_SRCS_QUOTED := 
OBJ_SRCS_QUOTED := 
LD_SRCS := 
CPP_SRCS_OS_FORMAT := 
C_UPPER_SRCS := 
C++_SRCS_OS_FORMAT := 
LD_SRCS_QUOTED := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
TOPREPROCESS_SRCS := 
C_SRCS := 
ASM_UPPER_SRCS_OS_FORMAT := 
CC_DEPS_OS_FORMAT := 
SECONDARY_FLASH_QUOTED := 
CPP_DEPS_QUOTED := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
CC_DEPS_QUOTED := 
CXX_DEPS_QUOTED := 
C_UPPER_DEPS_QUOTED := 
CXX_DEPS := 
C++_DEPS_OS_FORMAT := 
SECONDARY_SIZE_QUOTED := 
CPP_DEPS_OS_FORMAT := 
C++_DEPS_QUOTED := 
SECONDARY_SIZE_OS_FORMAT := 
C_DEPS_QUOTED := 
OBJS_QUOTED := 
C_DEPS := 
C_DEPS_OS_FORMAT := 
OBJS_OS_FORMAT := 
CC_DEPS := 
EXECUTABLES_OS_FORMAT := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_FLASH := 
CXX_DEPS_OS_FORMAT := 
C_UPPER_DEPS_OS_FORMAT := 
SECONDARY_FLASH_OS_FORMAT := 
EXECUTABLES_QUOTED := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Generated_Code \
Project_Settings/Linker_Files \
Project_Settings/Startup_Code \
SDK/platform/devices/S32K144/startup \
SDK/platform/devices \
SDK/platform/drivers/src/adc \
SDK/platform/drivers/src/clock/S32K1xx \
SDK/platform/drivers/src/clock \
SDK/platform/drivers/src/edma \
SDK/platform/drivers/src/flash \
SDK/platform/drivers/src/flexcan \
SDK/platform/drivers/src/ftm \
SDK/platform/drivers/src/interrupt \
SDK/platform/drivers/src/lpi2c \
SDK/platform/drivers/src/lpit \
SDK/platform/drivers/src/lpuart \
SDK/platform/drivers/src/pins \
SDK/platform/drivers/src/power/S32K1xx \
SDK/platform/drivers/src/power \
SDK/platform/drivers/src/wdog \
SDK/rtos/osif \
Sources/BSW/BswM \
Sources/BSW/CDDNIO \
Sources/BSW/Can \
Sources/BSW/CanIf \
Sources/BSW/CanNm \
Sources/BSW/CanSM \
Sources/BSW/CanTp \
Sources/BSW/CanTrcv_30_Tja1040 \
Sources/BSW/Com \
Sources/BSW/ComM \
Sources/BSW/Crc \
Sources/BSW/Dcm \
Sources/BSW/Dem \
Sources/BSW/Det \
Sources/BSW/EcuM \
Sources/BSW/Fee_30_SmallSector \
Sources/BSW/Fls \
Sources/BSW/MemIf \
Sources/BSW/Nm \
Sources/BSW/NvM \
Sources/BSW/Os \
Sources/BSW/PduR \
Sources/BSW/VStdLib \
Sources/NfcLibrary/NdefLibrary/src \
Sources/NfcLibrary/NxpNci/src \
Sources/NfcNio \
Sources/app/AutosarApp/GenData \
Sources/app/AutosarApp/Source \
Sources/app/Key \
Sources/app \
Sources/hal \
Sources \

